version: "3"

services:
  caddy:
    container_name: bem-caddy
    build:
      context: .
      dockerfile: caddy/Dockerfile
    image: bem-caddy:latest
    restart: on-failure
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "1337:1337"
    volumes:
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/caddy_config:/config
    networks:
      - bem-net
    depends_on:
      - osquery_be

  osquery_be:
    container_name: bem-osquery-be
    build:
      context: .
      dockerfile: Dockerfile # by default builds 'dev' image
    image: bem-osquery-be:latest
    working_dir: /app
    command:
      [
        "infisical",
        "run",
        "--",
        "uvicorn",
        "osquery_be.main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=8008",
        "--log-level=debug",
      ]
    volumes:
      - $PWD:/app
    restart: on-failure
    networks:
      - bem-net
    extra_hosts:
      - "host.docker.internal:host-gateway" # we need this to access host from container
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

networks:
  bem-net:
