services:
  redis-stack:
    container_name: bem-redis
    image: "redis/redis-stack:7.2.0-v8"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis-data:/data
    restart: unless-stopped