POST http://localhost:8090/osquery/enroll HTTP/1.1
Content-Type: application/json

{
    "api_key": "12345",
    "admin_email": "admin@localhost.dev"
}

###

POST http://localhost:8090/osquery/config HTTP/1.1
Content-Type: application/json

{
    "name": "sample"
}

###

GET http://localhost:8090/osquery/config HTTP/1.1
Content-Type: application/json

###
