version: '3'

services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: unless-stopped
    # ulimits:
    #   memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonfly:/data
    networks:
      - bem-net

volumes:
  dragonfly:

networks:
  bem-net: